version: '3'

services:
  front:
    image: timeovergrow
    container_name: 'timeovergrow-front'
    build: .
    tty: true
    command: yarn dev
    volumes:
      - './:/usr/src/app'
    ports:
      - '3000:3000'
